name: Update README Gallery

on:
  push:
    branches: [ main ]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: readme-gallery-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update-readme-gallery:
    if: ${{ !github.event.repository.fork }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure tools
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick ffmpeg
          convert -version
          ffmpeg -version

      # Render (re)generates assets; harmless if already present
      - name: Render latest trailer & CLI sim
        run: |
          mkdir -p assets
          node bin/release-cinema.mjs render --auto --preset linkedin --slide-seconds 3 --out-dir assets
          node bin/release-cinema.mjs simulate --out assets/cli_sim.gif

      - name: Update README gallery
        run: node scripts/update-gallery.mjs

      - name: Commit changes (if any)
        run: |
          git add README.md assets/trailer.gif assets/trailer.mp4 assets/cli_sim.gif || true
          if ! git diff --cached --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "docs(gallery): refresh README Gallery with latest trailer"
            git push
          else
            echo "No changes to commit."
          fi
