name: Release Cinema

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pull-requests: write

jobs:
  trailer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install system deps (ImageMagick, ffmpeg, fonts)
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick ffmpeg fonts-dejavu-core
          convert -version
          ffmpeg -version

      # --- Render trailer for PRs: base..head exact range ---
      - name: Render trailer (PR)
        if: ${{ github.event_name == 'pull_request' }}
        env:
          FROM_SHA: ${{ github.event.pull_request.base.sha }}
          TO_SHA:   ${{ github.event.pull_request.head.sha }}
        run: |
          node bin/release-cinema.mjs render \
            --from "$FROM_SHA" --to "$TO_SHA" \
            --preset linkedin \
            --out-dir assets

      # --- Render trailer on tag pushes (auto: last tag..this tag/HEAD) ---
      - name: Render trailer (tag)
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          node bin/release-cinema.mjs render \
            --auto \
            --preset linkedin \
            --out-dir assets

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trailer
          path: |
            assets/trailer.gif
            assets/trailer.mp4

      # Nice: embed the GIF in the workflow summary so reviewers can watch inline
      - name: Add Action Summary preview
        if: always()
        run: |
          echo "## 🎬 Release Cinema Preview" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo '<img alt="trailer" src="data:image/gif;base64,' >> "$GITHUB_STEP_SUMMARY"
          base64 -w 0 assets/trailer.gif >> "$GITHUB_STEP_SUMMARY" || true
          echo '"/>' >> "$GITHUB_STEP_SUMMARY"

      # PR comment: link to this run (artifacts + inline preview in Summary)
      - name: Comment on PR with links
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const runId = process.env.GITHUB_RUN_ID;
            const url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${runId}`;
            const body = [
              '🎬 **Release Cinema preview**',
              '',
              `• **GIF/MP4 artifacts & inline preview:** ${url}`,
              '',
              '_Open the run → Summary tab for the embedded GIF._'
            ].join('\n');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });

      # Attach media to the GitHub Release for tag builds
      - name: Attach to Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            assets/trailer.gif
            assets/trailer.mp4
